apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: demo-api
  name: demo-api
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-api
  template:
    metadata:
      labels:
        run: demo-api
    spec:
      containers:
      - image: lukebond/demo-api:demo-gods
        imagePullPolicy: Always
        name: demo-api
        ports:
        - containerPort: 9000
          protocol: TCP
      restartPolicy: Always
      securityContext: {}
